#general .yaml file

spark:
  config:
    spark.driver.bindAddress: localhost
    spark.ui.port: 4040
    spark.driver.memory: "12g"
    spark.driver.memoryOverhead: 4096
    spark.sql.shuffle.partitions: 8
    spark.default.parallelism: 8
    spark.master: "local[4]"
    spark.serializer: "org.apache.spark.serializer.KryoSerializer"

  dirs:
    temp_folder: "data/temp/"

parameters:
  subgraph_depth: 3
  weight_thresh: 0.6
  cosine_thresh: 0.6

input:
  name: Hamsterster
  delimiter: ","
  nodes:
    file_path: data/input_graphs/Hamsterster/nodes.csv
    has_header: True
    vector_size: 1
    delimiter: ","
    id_column_name:
      - ID
    features:
      - Species
      - Coloring
      #- Hometown
      #- Favorite_toy
      #- Favorite_activity
      #- Favorite_food
  edges:
    file_path: data/input_graphs/Hamsterster/edges.csv
    has_header: True
    has_weights: False
    delimiter: ","
